# Generated by Django 4.0.6 on 2022-07-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('sub_heading_0', models.CharField(max_length=500)),
                ('content0', models.TextField(max_length=500)),
                ('image0', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('sub_heading_1', models.CharField(max_length=500)),
                ('content1', models.TextField(max_length=500)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('sub_heading_2', models.CharField(max_length=500)),
                ('content2', models.TextField(max_length=500)),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
